name: 'Terraform Apply'
description: 'Terraform Composite action for terrafrom apply'

inputs:
  STATEBUCKET:
    description: 'statebucket name'
    required: true
    default: mybucksoham-cicd 
  ENVIRONMENT:
    description: 'environment name'
    required: true
    default: test
  REGION:
    description: 'region'
    required: true
    default: "ap-south-1"
  DIRECTORY:
    description: 'Working directory'
    required: true
    default: "s3-sqs-event"
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: cd ./services/${{inputs.DIRECTORY}} && terraform init -backend-config="bucket=${{inputs.STATEBUCKET}}" -backend-config="region=${{inputs.REGION}}"
      shell: bash
    - name: Terraform Apply
      run: cd ./services/${{inputs.DIRECTORY}} && terraform apply -auto-approve
      shell: bash
